### ISSUE TITLE
Drive-By-Wire Improvements/Analysis

### ISSUE THREAD

**Issue by jaiperis** [Nova-UTD/hardware#14]
We are gonna improve the drive-by-wire system. The algorithm/system for the wiring is good. The connections need to be improve. Also, we need to figure out how the voltage signal relates to the speed or torque or something. Also, whether the orange signal actually matters. Then, update the MCU firmware.

**Comment by jaiperis** [comment]
We got the new connectors, so now we can improve the wiring system!

**Comment by danielv012** [comment]
Throttle bypass done.
