### ISSUE TITLE
Spec cameras

### ISSUE THREAD

**Issue by jruths** [Nova-UTD/hardware#7]
Here is an example of an automotive/industrial grade line of cameras: [https://thinklucid.com/](https://thinklucid.com/)

**Comment by meyli1** [comment]
Google doc for anybody interested in doing more research on Power Over Ethernet (PoE) cameras: https://docs.google.com/document/d/1HqdwOfh-E7vD0OC0tGWWJLxN9HN-gms8jzxGqiUcFYU/edit?usp=sharing

Camera Must:
- Be power over Ethernet
- Be able to sustain external environment (Robust hefty camera)
- Low Memory taken up: (Lower resoulution or features that allow memory compression)
- All 4 cameras should be under a budget of ~$2000

Helpful google search start links:
- Surround View System
- PoE Industrial Camera
- Memory Compression PoE Cameras

**Comment by Abhi220180** [comment]
If we can get the current bandwidth that the ZED camera operates as well as the bandwidth reduction, it would smooth over the current research process.
